exports.C = {
	ADD_SONG: "ADD SONG",
	ADD_SONGS:"ADD_SONGS",
	UPDATE_SONG: "UPDATE SONG",
	REMOVE_SONG: "REMOVE SONG",
	ADD_CATEGORIE: "ADD CATEGORIE",
	UPDATE_CAT: "UPDATE CAT",
	REMOVE_CATEGORIE: "REMOVE CATEGORIE",
	SET_CURRENT_CAT: "SET CURRENT CAT",
	SET_CURRENT_SONG: "SET CURRENT SONG",
	CATLIST_VIEW: "CATLIST VIEW",
	FAVLIST_VIEW: "FAVLIST VIEW",
	STREAMLIST_VIEW: "STREAMLIST VIEW",
	SETTINGLIST_VIEW: "SETTINGLIST VIEW",
	CREATESTREAM_VIEW: "CREATESTREAM VIEW",
	CHANGE_INDEX: "CHANGE INDEX",
	ADD_TO_FAVORITE: "ADD TO FAVORITE",
	REMOVE_FROM_FAVORITE: "REMOVE FROM FAVORITE",
	CHANGE_DIRECTION: "CHANGE DIRECTION",
	UPDATE_SONG_LIST: "UPDATE SONG LIST",
	SEARCH_SONG: "SEARCH SONG",
	CHANGE_RESULT_VIEW: "CHANGE RESULT VIEW",
	CHANGE_ADD_CAT_VIEW: "CHANGE ADD CAT VIEW",
	CHANGE_ADD_SONG_VIEW: "CHANGE ADD SONG VIEW",
	CHANGE_VERSEDIV_NUMBER: "CHANGE_VERSEDIV_NUMBER",
	CHANGE_LANGUAGE: "CHANGE LANGUAGE",
	CHANGE_NIGHTMODE: "CHANGE NIGHT MODE",
	CHANGE_DEVTOOL_VIEW: "CHANGE DEVTOOL VIEW",
	SET_CONTROLS: "SET CONTROLS",
	SET_MESSAGE: "SET MESSAGE",
	SET_INCREMENT: "SET INCREMENT",
	SET_FORCEUPDATE: "SET FORCE UPDATE",
	SET_SELECTOR: "SET SELECTOR",
	SET_LOCAL_CAT: "SET LOCAL CAT",
	CLEAR_ONLINE_CAT: "CLEAR_ONLINE_CAT",
	SUBSCRIBE_TO_STREAM: "SUBSCRIBE TO STREAM",
	START_STREAM: "START STREAM",
	STOP_STREAM: "STOP STREAM",
	APP_REACHABLE: "APP REACHABLE",
	APP_UNREACHABLE: "APP UNREACHABLE",
	INITIALIZE_FAVORITE: "INITIALIZE FAVORITE"
}

exports.System = {
	LOCALSTORAGE: 'LOCAL'
}
exports.databasesOptions = {
	host: 		'localhost',
	user: 		'Abel',
	password: 	'Abel',
	database: 	'Songs'
}
exports.dev = {
	START_SQL_FILE: '/Users/flashbell/Node/Songs/utilis/startSql.js',
	LOG_FILE: 		'/var/log/Songs/modain.log',
	ERROR_LOG_FILE: '/var/log/Songs/error.log'
}